apiVersion: v1
kind: Service
metadata:
  name: employee-app-service
spec:
  type: NodePort
  selector:
    app: employee-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30080